# --------------------------------------------------------------  
# (C)Copyright 2001,2006,                                         
# International Business Machines Corporation,                    
# Sony Computer Entertainment, Incorporated,                      
# Toshiba Corporation,                                            
#                                                                 
# All Rights Reserved.                                            
# --------------------------------------------------------------  
# PROLOG END TAG zYx                                              

########################################################################
#			Target
########################################################################

PROGRAMS_spu	:= listrank_spu listrank_spu_step3
LIBRARY_embed	:= listrank_spu.a listrank_spu_step3.a

#CFLAGS = -DPROFILING
########################################################################
#			Local Defines
########################################################################

#IMPORTS 	= $(SDKLIB_spu)/libc.a


########################################################################
#                       make.footer
########################################################################

include ${MAKE_FOOTER}
