# --------------------------------------------------------------  
# (C)Copyright 2001,2006,                                         
# International Business Machines Corporation,                    
# Sony Computer Entertainment, Incorporated,                      
# Toshiba Corporation,                                            
#                                                                 
# All Rights Reserved.                                            
# --------------------------------------------------------------  
# PROLOG END TAG zYx                                              

########################################################################
#			Target
########################################################################

PROGRAM_ppu	= listrank
CFLAGS = -DVERIFY #-DPROFILING #-DOUTPUT

########################################################################
#			Local Defines
########################################################################

IMPORTS 	= ../spu/listrank_spu.a ../spu/listrank_spu_step3.a -lspe


########################################################################
#			make.footer
########################################################################

include ${MAKE_FOOTER}

